import js from "@eslint/js";
import tseslint from "typescript-eslint";
import vitest from "@vitest/eslint-plugin";
import prettier from "eslint-config-prettier";
import boundaries from "eslint-plugin-boundaries";
import n from "eslint-plugin-n";

// ── CF Workers: Node.js built-ins unavailable at runtime (ADR-0006) ─────────
const CF_WORKERS_NODE_MESSAGE =
  "Node.js built-in modules are not available in Cloudflare Workers. " +
  "Use WinterCG-compatible APIs instead. See ADR-0006.";

// Modules that are definitively absent in the Workers runtime.
// (crypto/buffer/streams/events have WinterCG equivalents — block only
//  the ones that have no CF Workers substitute at all.)
const BLOCKED_NODE_BUILTINS = [
  "child_process",
  "cluster",
  "dgram",
  "dns",
  "dns/promises",
  "domain",
  "fs",
  "fs/promises",
  "http",
  "https",
  "inspector",
  "net",
  "os",
  "path",
  "perf_hooks",
  "readline",
  "tls",
  "v8",
  "vm",
  "worker_threads",
];

// Build the n/no-restricted-import list covering both bare and node: forms.
const BLOCKED_IMPORTS = BLOCKED_NODE_BUILTINS.flatMap((name) => [
  { name, message: CF_WORKERS_NODE_MESSAGE },
  { name: `node:${name}`, message: CF_WORKERS_NODE_MESSAGE },
]);

export default tseslint.config(
  // ── Global ignores ───────────────────────────────────────────────────────
  // scripts/ are Node tooling (build-time), outside the Workers tsconfig.
  // .claude/ holds git worktrees the Claude Code harness creates; their
  // duplicated source has no linked node_modules, so type-aware linting there
  // fails to resolve workspace packages. Ignore them like other build output.
  {
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      "**/.wrangler/**",
      "**/scripts/**",
      "**/.claude/**",
      // .swarm/ is a mutation-testing scratch dir (~62k duplicated .ts files);
      // type-aware linting there OOMs locally. Mirrors the .claude/ precedent.
      "**/.swarm/**",
      // Generated by `wrangler types` (cf-typegen); a committed artifact, not hand-authored.
      "**/worker-configuration.d.ts",
      // Generated from openapi.json by `api:types`; likewise committed, not hand-authored.
      "apps/web/src/api/schema.ts",
      // Gallery PNG output is gitignored and never linted (#145).
      "apps/web/gallery/out/**",
    ],
  },

  // ── Layer boundary enforcement (ADR-0003) ────────────────────────────────
  // Elements map file paths → logical layer names.
  // The default "disallow" rule means a layer can only import from layers
  // explicitly listed in its `allow` entry.  The workspace package
  // @snaveevans/pineapple-shared resolves to packages/shared/** via the
  // TypeScript project service, so it is recognised as the "shared" element.
  {
    plugins: { boundaries },
    settings: {
      "boundaries/elements": [
        { type: "shared", pattern: "packages/shared/**" },
        { type: "domain", pattern: "apps/api/src/domain/**" },
        { type: "application", pattern: "apps/api/src/application/**" },
        { type: "infrastructure", pattern: "apps/api/src/infrastructure/**" },
        { type: "api-layer", pattern: "apps/api/src/api/**" },
        { type: "composition-root", pattern: "apps/api/src/worker.ts" },
      ],
    },
    rules: {
      "boundaries/dependencies": [
        "error",
        {
          default: "disallow",
          rules: [
            // shared has no internal deps — intentionally omitted
            { from: { type: "domain" }, allow: [{ to: { type: "shared" } }] },
            {
              from: { type: "application" },
              allow: [{ to: { type: "domain" } }, { to: { type: "shared" } }],
            },
            {
              from: { type: "infrastructure" },
              allow: [
                { to: { type: "application" } },
                { to: { type: "domain" } },
                { to: { type: "shared" } },
              ],
            },
            {
              from: { type: "api-layer" },
              allow: [
                { to: { type: "application" } },
                { to: { type: "domain" } },
                { to: { type: "shared" } },
              ],
            },
            // composition root (worker.ts) is the wiring point — no restrictions
            { from: { type: "composition-root" }, allow: [{ to: { type: "*" } }] },
          ],
        },
      ],
    },
  },

  // ── Core ESLint recommended rules ─────────────────────────────────────────
  // Must precede the tseslint blocks: tseslint's bundled eslint-recommended
  // disables core rules that TS handles better (no-unused-vars, no-redeclare,
  // …). A later core config would re-enable them for TS files. Placed here so
  // the type-aware block below overrides these for .ts files.
  js.configs.recommended,
  {
    rules: {
      // Swallowed errors hide bugs; require a comment or rethrow. Pinned
      // explicitly so an upstream default change can't silently re-allow it.
      "no-empty": ["error", { allowEmptyCatch: false }],
    },
  },

  // ── Type-aware TypeScript linting ────────────────────────────────────────
  {
    files: ["**/*.ts"],
    extends: tseslint.configs.recommendedTypeChecked,
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // `!` is the cheapest way to silence a nullability error; ban it so a
      // hidden null surfaces as a real bug instead. Fix or narrowly justify
      // each site — don't blanket-disable.
      "@typescript-eslint/no-non-null-assertion": "error",
    },
  },

  // ── Vitest: keep tests honest ─────────────────────────────────────────────
  // .only silently skips the rest of the suite; .skip / xit silently drop tests.
  // Both produce a green diff that hides a regression — fail CI on them.
  // Covers .test.ts and .test.tsx (the React component suites).
  {
    files: ["**/*.test.{ts,tsx}"],
    plugins: { vitest },
    rules: {
      "vitest/no-focused-tests": "error",
      "vitest/no-disabled-tests": "error",
    },
  },

  // ── TSX: non-type-checked linting ─────────────────────────────────────────
  // .tsx files are outside the Workers tsconfig and were previously ignored by
  // eslint entirely (no matching config). Full type-checked linting of the
  // React app is a separate concern — extending recommendedTypeChecked here
  // surfaces ~50 unrelated errors (floating-promises, require-await,
  // unbound-method, …) across apps/web. Instead, extend the non-type-checked
  // recommended set so the TS parser is engaged and conflicting core rules
  // (no-undef, no-unused-vars, …) from js.configs.recommended are disabled,
  // then layer on this PR's `!` ban. This closes the gap the review flagged —
  // four `!`s in .tsx sat outside the ban — without ballooning into a full
  // type-checked-lint-of-the-web-client branch.
  {
    files: ["**/*.tsx"],
    extends: tseslint.configs.recommended,
    rules: {
      "@typescript-eslint/no-non-null-assertion": "error",
    },
  },

  // ── CF Workers runtime constraint (ADR-0006) ─────────────────────────────
  // Flag any import of a Node.js built-in module inside the API app.
  // process.env is also blocked — use wrangler env bindings instead.
  {
    files: ["apps/api/src/**/*.ts"],
    plugins: { n },
    rules: {
      "n/no-restricted-import": ["error", BLOCKED_IMPORTS],
      "n/no-process-env": "error",
    },
  },

  // ── CF Workers: no floating promises ─────────────────────────────────────
  // Workers silently drops un-awaited promises: work is dropped and errors
  // are swallowed. recommendedTypeChecked already enables this rule
  // repo-wide; pin it explicitly for the API so the guarantee survives
  // future config changes. Intentionally-detached work must use `void`.
  {
    files: ["apps/api/src/**/*.ts"],
    rules: {
      "@typescript-eslint/no-floating-promises": "error",
    },
  },

  // ── Non-type-aware linting for JS/CJS config files ───────────────────────
  {
    files: ["**/*.{js,mjs,cjs}"],
    extends: tseslint.configs.recommended,
  },

  prettier,
);
