/**
 * Hand-authored deferred gallery states. A FEATURES.md id with no entry here
 * (and no rendered/excluded entry) fails the coverage check — do not auto-fill.
 */
export type DeferredEntry = {
  id: string;
  category: "deferred";
  issue: number;
  reason: string;
};

export const DEFERRED: DeferredEntry[] = [
  {
    id: "marketing-home/unauthenticated",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "marketing-home/authenticated",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "sign-in/idle",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "sign-in/in-flight",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "sign-in/error",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "user-profile-and-onboarding/loading",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "user-profile-and-onboarding/error",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "user-profile-and-onboarding/populated-incomplete-onboarding-provider-name-available",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "user-profile-and-onboarding/populated-incomplete-onboarding-no-provider-name",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "user-profile-and-onboarding/populated-profile-edit",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "user-profile-and-onboarding/contact-email-unset",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "user-profile-and-onboarding/contact-email-unverified",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "user-profile-and-onboarding/contact-email-verified",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "user-profile-and-onboarding/mutation-pending-patch-api-users-me-display-name",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "user-profile-and-onboarding/mutation-pending-set-contact-email-put-api-users-me-notification-email",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "user-profile-and-onboarding/mutation-pending-remove-contact-email-delete-api-users-me-notification-email",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "user-profile-and-onboarding/mutation-pending-resend-verification-post-api-users-me-notification-email-verification",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "user-profile-and-onboarding/mutation-error",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "user-profile-and-onboarding/notice-saved",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "user-profile-and-onboarding/notice-verification-sent",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "user-profile-and-onboarding/notice-removed",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "user-profile-and-onboarding/notice-cooldown",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "user-profile-and-onboarding/content-stress-maximum-length-display-name",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "user-profile-and-onboarding/content-stress-long-contact-email-address",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "authenticated-app-shell/desktop",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "authenticated-app-shell/mobile",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "authenticated-app-shell/active-route",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "authenticated-app-shell/loading-profile",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "authenticated-app-shell/populated-profile",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "authenticated-app-shell/error-profile",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "authenticated-app-shell/loading-notifications",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "authenticated-app-shell/populated-notifications-zero-unread",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "authenticated-app-shell/populated-notifications-has-unread",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "authenticated-app-shell/error-notifications",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "notifications/mutation-pending-mark-one-read",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "notifications/mutation-pending-mark-all-read",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "notifications/mutation-error",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "notifications/content-stress-long-asset-name-in-notification-rows",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "notifications/content-stress-long-task-title",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "notifications/content-stress-collection-at-pagination-boundary",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "dashboard-home/loading",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "dashboard-home/error",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "dashboard-home/empty-empty-fleet",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "dashboard-home/empty-no-scheduled-tasks",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "dashboard-home/empty-filtered",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "dashboard-home/populated",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "dashboard-home/mutation-pending-mark-complete",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "dashboard-home/mutation-pending-add-service",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "dashboard-home/mutation-error",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "dashboard-home/add-service-drawer-loading",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "dashboard-home/add-service-drawer-error",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "dashboard-home/add-service-drawer-empty",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "dashboard-home/content-stress-long-asset-name-in-queue-rows-and-detail-card",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "dashboard-home/content-stress-long-task-title",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "dashboard-home/content-stress-long-owner-display-name-in-sharing-badge",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "asset-library/content-stress-long-asset-name-on-cards",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "asset-library/content-stress-long-owner-display-name-in-sharing-badge",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "asset-library/content-stress-long-property-address-in-property-card-summaries",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "app-search/closed",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "app-search/open-idle-empty-query",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "app-search/loading",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "app-search/error",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "app-search/empty-no-matches",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "app-search/populated",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "app-search/content-stress-long-asset-name-in-result-rows",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "app-search/content-stress-long-summary-line",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "app-search/content-stress-long-owner-display-name-in-sharing-badge",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "activity-history/content-stress-long-asset-name-in-entries",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "activity-history/content-stress-long-action-title",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "activity-history/content-stress-long-teammate-display-name-in-actor-attribution",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "activity-history/content-stress-collection-at-pagination-boundary",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "add-asset/idle-vehicle-type",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "add-asset/idle-property-type",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "add-asset/idle-equipment-type",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "add-asset/mutation-pending",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "add-asset/mutation-error-client-validation",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "add-asset/mutation-error-api",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "add-asset/content-stress-long-asset-name",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "add-asset/content-stress-long-property-address",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "asset-maintenance-records-and-tasks/loading",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "asset-maintenance-records-and-tasks/error-forbidden-403",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "asset-maintenance-records-and-tasks/error-not-found-404",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "asset-maintenance-records-and-tasks/error-load-failure",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "asset-maintenance-records-and-tasks/empty-no-records",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "asset-maintenance-records-and-tasks/empty-no-tasks",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "asset-maintenance-records-and-tasks/populated",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "asset-maintenance-records-and-tasks/populated-shared-by-teammate",
    category: "deferred",
    issue: 192,
    reason: "Remaining read states (slice 2)",
  },
  {
    id: "asset-maintenance-records-and-tasks/mutation-pending-create-record",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "asset-maintenance-records-and-tasks/mutation-pending-create-task",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "asset-maintenance-records-and-tasks/mutation-pending-share-unshare-owner-only",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "asset-maintenance-records-and-tasks/mutation-error",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "asset-maintenance-records-and-tasks/local-delete-task-confirm",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "asset-maintenance-records-and-tasks/content-stress-long-asset-name-in-header",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "asset-maintenance-records-and-tasks/content-stress-long-record-description",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "asset-maintenance-records-and-tasks/content-stress-long-task-title",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "asset-maintenance-records-and-tasks/content-stress-long-owner-display-name-in-sharing-badge",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "team/mutation-pending-create-team",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "team/mutation-error-validation",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "team/mutation-error-409-conflict",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "team/mutation-error-api",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "team/content-stress-long-team-name",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
  {
    id: "team/content-stress-long-member-display-name",
    category: "deferred",
    issue: 193,
    reason: "Mutation / local / content-stress gallery states (slice 3)",
  },
];
