import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";
import { ScreenSpec, copyText } from "./schema.ts";

// Reads the authored YAML, validates it, and writes the generated artifacts:
//   generated/ux.json  — machine-readable spec (the openapi.json analogue)
//   generated/copy.ts  — typed copy catalog the implementations import
//
// Mirrors `openapi:generate`: regenerate, then `git diff --exit-code`.

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const screensDir = join(pkgRoot, "screens");
const outDir = join(pkgRoot, "generated");

function loadScreens(): ScreenSpec[] {
  return readdirSync(screensDir)
    .filter((file) => file.endsWith(".yaml"))
    .sort()
    .map((file) => {
      const raw: unknown = parse(readFileSync(join(screensDir, file), "utf8"));
      const result = ScreenSpec.safeParse(raw);
      if (!result.success) {
        const detail = result.error.issues
          .map((issue) => `  ${issue.path.join(".") || "(root)"}: ${issue.message}`)
          .join("\n");
        throw new Error(`${file} failed validation:\n${detail}`);
      }
      return result.data;
    });
}

function toCopyCatalog(screens: ScreenSpec[]): Record<string, Record<string, string>> {
  const catalog: Record<string, Record<string, string>> = {};
  for (const screen of screens) {
    for (const state of screen.states) {
      for (const [key, value] of Object.entries(state.copy)) {
        const id = `${screen.id}.${state.id}`;
        catalog[id] = { ...catalog[id], [key]: copyText(value) };
      }
      for (const action of state.actions) {
        const id = `${screen.id}.${state.id}.action.${action.id}`;
        catalog[id] = { label: action.label };
      }
    }
  }
  return catalog;
}

function renderCopyModule(catalog: Record<string, Record<string, string>>): string {
  const body = Object.entries(catalog)
    .map(([id, strings]) => {
      const fields = Object.entries(strings)
        .map(([key, text]) => `    ${key}: ${JSON.stringify(text)},`)
        .join("\n");
      return `  ${JSON.stringify(id)}: {\n${fields}\n  },`;
    })
    .join("\n");

  return [
    "// GENERATED by @snaveevans/pineapple-ux-spec — do not edit.",
    "// Source: packages/ux-spec/screens/*.yaml",
    "",
    "export const copy = {",
    body,
    "} as const;",
    "",
    "export type CopyId = keyof typeof copy;",
    "",
  ].join("\n");
}

const screens = loadScreens();
mkdirSync(outDir, { recursive: true });

writeFileSync(join(outDir, "ux.json"), `${JSON.stringify({ screens }, null, 2)}\n`, "utf8");
writeFileSync(join(outDir, "copy.ts"), renderCopyModule(toCopyCatalog(screens)), "utf8");

const stateCount = screens.reduce((total, screen) => total + screen.states.length, 0);
console.log(`ux-spec: generated ${screens.length} screen(s), ${stateCount} state(s)`);
